name: Compile and Lint ğŸ”¨

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Yarn Install ğŸ“¦
        run: |
          yarn
      - name: Linting ğŸ§¹
        run: |
          yarn lint
      - name: Fetch OpenRCT2 Scripting Api
        run: |
          cd lib
          sh FetchOpenRCT2Api.sh
          cd ..
      - name: Compiler ğŸ—ï¸
        run: |
          yarn build
